### ISSUE TITLE
Want to add web scraping.

### ISSUE THREAD

**Issue by stamarty** [stamarty/WordCounter#5]

**Comment by stamarty** [comment]
Just like it sounds. I want to do a search on a job search site and have the program scrape the keywords then move to the next posting.

**Comment by Kunal614** [comment]
What do you want , linking with linkedin so that you get data of any job , or anything else?

**Comment by stamarty** [comment]
> What do you want , linking with linkedin so that you get data of any job , or anything else?

I was thinking specifically scraping from glassdoor, but linkedIn job pages would be fine too. I'm specifically looking to pull the job descriptions from the pages.

**Comment by stamarty** [comment]
![This spot here](https://user-images.githubusercontent.com/7009764/68141362-395d7180-fee2-11e9-9421-f7ab148da57c.JPG)
This is the block here, that I'm talking about. I want to be able to pull this data into the text reader and count the frequency of the words showing up.

**Comment by Kunal614** [comment]
can you share the block link?

**Comment by stamarty** [comment]
I'm not certain I understand the term "block link". Do you mean div id? If so, here's a screenshot I hope will help. 
![block link](https://user-images.githubusercontent.com/7009764/68232761-a3454c00-ffb2-11e9-8397-b15e921d171f.JPG)

**Comment by Kunal614** [comment]
no no no ... Where is this block available

**Comment by stamarty** [comment]
Oh, that's at [https://www.glassdoor.com/index.htm](glassdoor)

**Comment by Kunal614** [comment]
I need your help , As i scrapped data from the given site but , i have a
query that how to calculate each and every word frequency?
can you help me .

**Comment by stamarty** [comment]
Is the word counter not working? 
What I'm hearing here is that you were able to scrape the site, but you don't know how to use the word count functionality? 

Are you following the directions in the readme? If so, what error are you getting so I can look into it. Thanks!

**Comment by Kunal614** [comment]
OK I will show you soon.

**Comment by stamarty** [comment]
That would be great! I'm not certain what your are asking me so any explanation would be helpful.

**Comment by Kunal614** [comment]
no no i understood.

**Comment by Kunal614** [comment]
https://www.glassdoor.com/index.htm
<http://glassdoor>

This link is not working , on click it says  trouble in finding this site

**Comment by stamarty** [comment]
https://www.glassdoor.com/ works fine for me. I'm not sure why you're having problems.

**Comment by Kunal614** [comment]
Sir here extracting of data's are not allowed , can i give you the code of
counting frequency of some different site?

[<p><b>type</b> Status report</p>, <p><b>message</b> <u>Bots not
allowed</u></p>, <p><b>description</b> <u>Access to the specified resource
has been forbidden
.</u></p>]
This comes.

**Comment by stamarty** [comment]
Oh, interesting. I didn't know think that was there. You can use any aggregate job site. 
https://www.linkedin.com/jobs/search/
https://www.indeed.com/jobs?q&l=Coquille%2C%20OR&ts=1571848911055&rq=1&rsIdx=1&fromage=last&newcount=163&advn=862219100656716&vjk=776ae8c79b223017


Anything like that.

**Comment by Kunal614** [comment]
sir , work  completed
please send me the link where i will do a pull request ?

**Comment by Kunal614** [comment]
pull request done  
link ->
 https://github.com/Kunal614/WordCounter/blob/master/count_freq_job.py

**Comment by stamarty** [comment]
Thanks. Merged!

**Comment by Kunal614** [comment]
welcome , Ready for more.
